package com.supplierportal.domain.audit;

public enum AuditActionType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_ROLE_CHANGED,
    USER_STATUS_CHANGED,
    SUPPLIER_REGISTERED,
    SUPPLIER_SUBMITTED,
    SUPPLIER_VALIDATED,
    SUPPLIER_REJECTED,
    SUPPLIER_SUSPENDED,
    DOCUMENT_UPLOADED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    EVALUATION_RECORDED,
    NOTIFICATION_SENT,
    NOTIFICATION_READ
}
